### ISSUE TITLE
visualization updates

### ISSUE THREAD

**Issue by mcfrank** [langcog/irw_site#6]
- [x] add dichotomous/polytomous as a split variable for color, not on by default
- [x] @ben-domingue provides a static plot of an individual dataset, 
- [x] then @mikabr converts to a "dataset selector" plot

**Comment by ben-domingue** [comment]
a simple static plot available here: https://domingue-lab.slack.com/archives/C05T1H6MEH4/p1697230453276049

code as well:

`load("florida_twins_behavior.Rdata")
unique(df$resp)
pvalue<-by(df$resp,df$item,mean,na.rm=TRUE)
hist(pvalue,xlim=range(df$resp,na.rm=TRUE),xlab='ctt p-value',ylab='',main='') 

ni<-length(unique(df$item))
L<-split(df,df$id)
n<-sapply(L,function(x) nrow(x)/ni)
z<-sapply(L,function(x) mean(x$resp,na.rm=TRUE))
plot(n,z,pch=19,cex=.5,xlab='proportion of items',ylab='average score')`
